### ISSUE TITLE
Selecting wrong UIs

### ISSUE THREAD

**Issue by GReaperEx** [shanemacbride/textRealm#2]
For any selection from 1 through 5, the opposite UI is chosen. Is this intentional? What I mean is:
I press 1: UI 5 is chosen
I press 2: UI 4 is chosen
I press 3: UI 3 is chosen
I press 4: UI 2 is chosen
I press 5: UI 1 is chosen
I press 6: UI 6 is chosen

If it's just a mistake, you should change the enum MenuChoice to:
```
enum MenuChoice
{
    m_none      = 0,
    m_key       = 5,
    m_controls  = 4,
    m_desc      = 3,
    m_abilities = 2,
    m_inventory = 1,
    m_events    = 6
};
```
or invert the corresponding switch case, whichever suits you best.

**Comment by shanemacbride** [comment]
Thanks @GReaperEx! I went ahead and changed it according to your suggestion; you're spot on. In the future, feel free to create Pull Requests as well.
