### ISSUE TITLE
Horizontal UI

### ISSUE THREAD

**Issue by GReaperEx** [shanemacbride/textRealm#8]
I've been thinking that there should be some way to place the UI beside the map instead of above, so that those of us who don't have enough vertical real-estate( smaller screens or larger letters for easier reading ) can just extend the terminal window horizontally and have almost the same experience.

Maybe the game should ask the user, before anything else, whether they'd like vertical or horizontal mode, and act accordingly. I think that in horizontal mode, the UI indicators( 1 [2] 3 ... ) should be placed vertically at the right side of the grid. If a UI is selected it should appear even more to the right, its bottom aligned with the bottom of the grid.

What do you say? I could start developing the change already, but I wanted to read your opinion first, so as to not code in vain in case you didn't want it. If you agree, please tell me so and leave this issue open for me to reference in an upcoming pull request, unless you want to code the change yourself...

**Comment by shanemacbride** [comment]
That makes sense to me :smiley:

**Comment by GReaperEx** [comment]
Cool. I will start working on it then.
